var pokemonList = {
  'Bulbasaur': ['bulbasaur', 'bul', 'ba', 'saur'],
  'Ivysaur': ['ivysaur', 'ivy', 'saur'],
  'Venusaur': ['venusaur', 'venu', 'saur'],
  'Charmander': ['charmander', 'char', 'man'],
  'Charmeleon': ['charmeleon', 'char', 'mel', 'meleon'],
  'Charizard': ['charizard', 'char', 'zard'],
  'Squirtle': ['squirtle', 'squirt'],
  'Wartortle': ['wartortle', 'war', 'tort'],
  'Blastoise': ['blastoise', 'blast', 'toise'],
  'Caterpie': ['caterpie', 'ca', 'cater', 'pi'],
  'Metapod': ['metapod', 'me', 'meta', 'pod'],
  'Butterfree': ['free', 'ee'],
  'Weedle': ['weedle', 'weed'],
  'Kakuna': ['kakuna', 'ka', 'ku', 'na'],
  'Beedrill': ['beedrill', 'bee', 'drill'],
  'Pidgey': ['pidgey', 'pid', 'gey'],
  'Pidgeotto': ['pidgeotto', 'pidgeo', 'to'],
  'Pidgeot': ['pidgeot', 'pid', 'geot'],
  'Rattata': ['rattata', 'rat', 'tata', 'ta'],
  'Raticate': ['raticate', 'rat', 'cate'],
  'Spearow': ['spearow', 'spear', 'row'],
  'Fearow': ['fearow', 'fear', 'row'],
  'Ekans': ['ekans', 'ek', 'kans', 'sss'],
  'Arbok': ['arbok', 'ar', 'bok'],
  'Pikachu': ['pikachu', 'pi', 'pika', 'chu'],
  'Raichu': ['raichu', 'rai', 'chu'],
  'Sandshrew': ['sandshrew', 'sand', 'shrew'],
  'Sandslash': ['sandslash', 'sand', 'slash'],
  'Nidoran ♀': ['nidoran', 'nido', 'ran'],
  'Nidorina': ['nidorina', 'nido', 'rina'],
  'Nidoqueen': ['nidoqueen', 'nido', 'queen'],
  'Nidoran ♂': ['nidoran', 'nido', 'ran'],
  'Nidorino': ['nidorino', 'nido', 'rino'],
  'Nidoking': ['nidoking', 'nido', 'king'],
  'Clefairy': ['clefairy', 'cle', 'fairy'],
  'Clefable': ['clefable', 'cle', 'fable'],
  'Vulpix': ['vulpix', 'vul', 'pix'],
  'Ninetales': ['ninetales', 'nine', 'tales'],
  'Jigglypuff': ['jigglypuff', 'jiggly', 'puff'],
  'Wigglytuff': ['wigglytuff', 'wiggly', 'tuff'],
  'Zubat': ['zubat', 'zu', 'bat'],
  'Golbat': ['golbat', 'gol', 'bat'],
  'Oddish': ['oddish', 'odd', 'ish'],
  'Gloom': ['gloom'],
  'Vileplume': ['vileplume', 'vile', 'plume'],
  'Paras': ['paras', 'par'],
  'Parasect': ['parasect', 'par', 'para', 'sect'],
  'Venonat': ['venonat', 'ven', 'veno', 'nat'],
  'Venomoth': ['venomoth', 'ven', 'veno', 'moth'],
  'Diglett': ['diglett', 'dig'],
  'Dugtrio': ['dugtrio', 'dug', 'trio', 'trio', 'trio'],
  'Meowth': ['this space intentionally left blank'],
  'Persian': ['persian', 'per', 'sian']
}

var pokemonListLength = Object.keys(pokemonList).length
