var pokemonList = {
  'Bulbasaur': ['bulbasaur', 'bul', 'ba', 'saur'],
  'Ivysaur': ['ivysaur', 'ivy', 'saur'],
  'Venusaur': ['venusaur', 'venu', 'saur'],
  'Charmander': ['charmander', 'char', 'man'],
  'Charmeleon': ['charmeleon', 'char', 'mel', 'meleon'],
  'Charizard': ['charizard', 'char', 'zard'],
  'Squirtle': ['squirtle', 'squirt'],
  'Wartortle': ['wartortle', 'war', 'tort'],
  'Blastoise': ['blastoise', 'blast', 'toise'],
  'Caterpie': ['caterpie', 'ca', 'cater', 'pi'],
  'Metapod': ['metapod', 'me', 'meta', 'pod'],
  'Butterfree': ['free', 'ee'],
  'Weedle': ['weedle', 'weed'],
  'Kakuna': ['kakuna', 'ka', 'ku', 'na'],
  'Beedrill': ['beedrill', 'bee', 'drill'],
  'Pidgey': ['pidgey', 'pid', 'gey'],
  'Pidgeotto': ['pidgeotto', 'pidgeo', 'to'],
  'Pidgeot': ['pidgeot', 'pid', 'geot'],
  'Rattata': ['rattata', 'rat', 'tata', 'ta'],
  'Raticate': ['raticate', 'rat', 'cate'],
  'Spearow': ['spearow', 'spear', 'row'],
  'Fearow': ['fearow', 'fear', 'row'],
  'Ekans': ['ekans', 'ek', 'kans', 'sss'],
  'Arbok': ['arbok', 'ar', 'bok'],
  'Pikachu': ['pikachu', 'pi', 'pika', 'chu'],
  'Raichu': ['raichu', 'rai', 'chu'],
  'Sandshrew': ['sandshrew', 'sand', 'shrew'],
  'Sandslash': ['sandslash', 'sand', 'slash'],
  'Nidoran ♀': ['nidoran', 'nido', 'ran'],
  'Nidorina': ['nidorina', 'nido', 'rina'],
  'Nidoqueen': ['nidoqueen', 'nido', 'queen'],
  'Nidoran ♂': ['nidoran', 'nido', 'ran'],
  'Nidorino': ['nidorino', 'nido', 'rino'],
  'Nidoking': ['nidoking', 'nido', 'king'],
  'Clefairy': ['clefairy', 'cle', 'fairy'],
  'Clefable': ['clefable', 'cle', 'fable'],
  'Vulpix': ['vulpix', 'vul', 'pix'],
  'Ninetales': ['ninetales', 'nine', 'tales'],
  'Jigglypuff': ['jigglypuff', 'jiggly', 'puff'],
  'Wigglytuff': ['wigglytuff', 'wiggly', 'tuff'],
  'Zubat': ['zubat', 'zu', 'bat'],
  'Golbat': ['golbat', 'gol', 'bat'],
  'Oddish': ['oddish', 'odd', 'ish'],
  'Gloom': ['gloom'],
  'Vileplume': ['vileplume', 'vile', 'plume'],
  'Paras': ['paras', 'par'],
  'Parasect': ['parasect', 'par', 'para', 'sect'],
  'Venonat': ['venonat', 'ven', 'veno', 'nat'],
  'Venomoth': ['venomoth', 'ven', 'veno', 'moth'],
  'Diglett': ['diglett', 'dig'],
  'Dugtrio': ['dugtrio', 'dug', 'trio', 'trio', 'trio'],
  'Meowth': ['this space intentionally left blank'],
  'Persian': ['persian', 'per', 'sian'],
  'Psyduck': ['psyduck', 'psy', 'yi', 'duck'],
  'Golduck': ['golduck', 'gol', 'duck'],
  'Mankey': ['mankey', 'man', 'key'],
  'Primeape': ['primeape', 'prime', 'ape'],
  'Growlithe': ['growlithe', 'growl', 'lithe'],
  'Arcanine': ['arcanine', 'arc', 'ca', 'canine'],
  'Poliwag': ['poliwag', 'po', 'poli', 'wag'],
  'Poliwhirl': ['poliwhirl', 'po', 'poli', 'whirl'],
  'Poliwrath': ['poliwrath', 'po', 'poli', 'wrath'],
  'Abra': ['abra', 'ab', 'ra'],
  'Kadabra': ['kadabra', 'ka', 'dab', 'ra'],
  'Alakazam': ['alakazam', 'ala', 'ka', 'zam'],
  'Machop': ['machop', 'ma', 'chop'],
  'Machoke': ['machoke', 'ma', 'choke'],
  'Machamp': ['machamp', 'ma', 'champ'],
  'Bellsprout': ['bellsprout', 'bell', 'sprout'],
  'Weepinbell': ['weepinbell', 'weep', 'pin', 'bell'],
  'Victreebel': ['victreebel', 'vic', 'tree', 'bel'],
  'Tentacool': ['tentacool', 'ten', 'ta', 'cool'],
  'Tentacruel': ['tentacruel', 'ten', 'ta', 'cruel'],
  'Geodude': ['geodude', 'geo', 'dude'],
  'Graveler': ['graveler', 'gra', 'vel'],
  'Golem': ['golem', 'go', 'lem'],
  'Ponyta': ['ponyta', 'po', 'ny', 'pony', 'ta'],
  'Rapidash': ['rapidash', 'ra', 'pi', 'rapi', 'dash'],
  'Slowpoke': ['slowpoke', 'slow', 'poke'],
  'Slowbro': ['slowbro', 'slow', 'bro'],
  'Magnemite': ['magnemite', 'mag', 'ne', 'mite'],
  'Magneton': ['magneton', 'mag', 'ne', 'ton'],
  'Farfetch\'d': ['farfetch\'d', 'far', 'fetch'],
  'Doduo': ['doduo', 'do', 'duo'],
  'Dodrio': ['dodrio', 'do', 'drio'],
  'Seel': ['seel'],
  'Dewgong': ['dewgong', 'dew', 'gong'],
  'Grimer': ['grimer', 'gri', 'mer', 'grime'],
  'Muk': ['muk'],
  'Shellder': ['shellder', 'shell'],
  'Cloyster': ['cloyster', 'cloy'],
  'Gastly': ['gastly', 'gas', 'tly'],
  'Haunter': ['haunter', 'haunt'],
  'Gengar': ['gengar', 'gen', 'gar'],
  'Onix': ['onix', 'on', 'ix'],
  'Drowsee': ['drowsee', 'drow', 'see'],
  'Hypno': ['hypno', 'hyp', 'no'],
  'Krabby': ['krabby', 'krab'],
  'Kingler': ['kingler', 'king', 'ler'],
  'Voltorb': ['voltorb', 'volt', 'orb'],
  'Electrode': ['electrode', 'elec', 'trode'],
  'Exeggcute': ['exeggcute', 'ex', 'egg', 'cute'],
  'Exeggutor': ['exeggutor', 'ex', 'egg', 'tor'],
  'Cubone': ['cubone', 'cu', 'bone'],
  'Marowak': ['marowak', 'ma', 'ro', 'wak'],
  'Hitmonlee': ['hitmonlee', 'hit', 'mon', 'lee'],
  'Hitmonchan': ['hitmonchan', 'hit', 'mon', 'chan'],
  'Lickitung': ['lickitung', 'lick', 'tung'],
  'Koffing': ['koffing', 'koff'],
  'Weezing': ['weezing', 'weez'],
  'Rhyhorn': ['rhyhorn', 'rhy', 'horn'],
  'Rhydon': ['rhydon', 'rhy', 'don'],
  'Chansey': ['chansey', 'chanse'],
  'Tangela': ['tangela', 'tan', 'ge', 'la', 'gela'],
  'Kangaskhan': ['kangaskhan', 'kan', 'ga', 'kanga', 'skhan'],
  'Horsea': ['horsea', 'hor', 'sea'],
  'Seadra': ['seadra', 'sea', 'dra'],
  'Goldeen': ['goldeen', 'gol', 'deen'],
  'Seaking': ['seaking', 'sea', 'king'],
  'Staryu': ['staryu', 'star', 'yu'],
  'Starmie': ['starmie', 'star', 'mie'],
  'Mr. Mime': ['mr. mime', 'mime'],
  'Scyther': ['scyther', 'scy', 'scythe'],
  'Jynx': ['jynx'],
  'Electabuzz': ['electabuzz', 'ele', 'buzz'],
  'Magmar': ['magmar', 'mag', 'mar'],
  'Pinsir': ['pinsir', 'pin', 'sir'],
  'Tauros': ['tauros', 'taur'],
  'Magikarp': ['magikarp', 'karp'],
  'Gyarados': ['gyarados', 'gyar', 'dos'],
  'Lapras': ['lapras', 'lap', 'ras'],
  'Ditto': ['ditto', 'di', 'tto'],
  'Eevee': ['eevee', 'ee', 'vee'],
  'Vaporeon': ['vaporeon', 'va', 'por', 'vapor', 'eon'],
  'Jolteon': ['jolteon', 'jolt', 'eon'],
  'Flareon': ['flareon', 'flare', 'eon'],
  'Porygon': ['this space intentionally left blank']
}

var pokemonListLength = Object.keys(pokemonList).length
